* Tomorg
** Tasks
*** DONE Get feedback on the Forward Planning Doc
SCHEDULED: <2026-08-27 Thu>
*** DONE pay bills and cash in car reports
SCHEDULED: <2026-08-27 Thu>
*** DONE Go to the library pre trip
SCHEDULED: <2026-08-27 Thu>
*** DONE Pack for the trip
SCHEDULED: <2026-08-28 Fri>
*** DONE work on a device to take on the trip
SCHEDULED: <2026-08-27 Thu>
*** TODO Take a photo of the garden and email to work power
SCHEDULED: <2026-09-20 Sun>
*** DONE Remember to weigh yourself
SCHEDULED: <2026-08-28 Fri>
** Events
*** Meet with Ichtus
<2026-08-28 Fri 16:00>
*** Start our trip fly to Adelaide
<2026-08-29 Sat 07:10>
SCHEDULED: <2026-08-29 Sat>
*** Dinner for Nanna and Maria 8 slices
SCHEDULED: <2026-08-26 Wed>
*** Athletics carnival
<2026-08-28 Fri>
*** 
<2026-08-28 Fri 16:00>
** Completed Tasks
** Bills
*** TODO Pay the rates 
SCHEDULED: <2026-09-18 Fri>
** Notes
*** Trip to Adelaide
**** Day 1
- Had a good flight. got in 10 mins late.
- We are staying at TRYP and it's really nice, and affordable.
- Had lunch at a cafe in the central markets.
- We had dinner at the coopers alehouse had a bean curry.
**** Day 2
- Got up at 6 and walked around Adelaide. 
- We had Brunch at Peter rabbit Cafe. The stuffed up order 3 times good food, terrible service
- Caught an Uber out to glenelg Jetty and Marina. Had a drink and then caught the Tram back to Adelaide. The tram cost $1 and was tapped with our Credit card very easy.
- We had dinner at a greek restaurant. Food was very good.
**** Day 3
- exercised on the treadmill in the hotel.
- picked up the motorhome.
- drove Maggie beer farm and had a coffee. this was where her cooking show was filmed.
- had lunch in 
- drove to Grant Burge winery for wine tasting.
- stayed in mt Barker and it was a surprisingly big town. bought a belt and a mattress topper for our bed.
**** Day 4
- drove n most of the day on our way to the grampian in Victoria.
- stopped att bordertown and in Horsham on our way.


